apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: springboot-openapi
  title: Spring Boot Service with OpenAPI
  description: Generate a Spring Boot application with OpenAPI and CRUD
  tags:
    - springboot
    - openapi
    - java
spec:
  path: ./template.yaml
  owner: team-owner
  type: service
