apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: springboot-openapi
  title: Spring Boot Service with OpenAPI
  description: Generate a Spring Boot application with OpenAPI and CRUD functionality
  tags:
    - java
    - springboot
    - openapi
spec:
  owner: team-owner
  type: service
  parameters:
    - title: Service Details
      required:
        - name
      properties:
        name:
          type: string
          title: Service Name
  steps:
    - id: fetch-repository
      name: Fetch Template Repository
      action: fetch:template
      input:
        url: https://github.com/digitalinnovationone/spring-boot-3-rest-api-template.git
        targetPath: .
        branch: main
    - id: register
      name: Register in Backstage
      action: catalog:register
      input:
        catalogInfoPath: ./catalog-info.yaml
