name: Create Repository from Template

on:
  workflow_dispatch:
    inputs:
      username:
        description: "GitHub username or organization where the repository will be created"
        required: true
      reponame:
        description: "Name of the repository to create"
        required: true

jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Log Inputs
        run: |
          echo "Creating repository for user: ${{ inputs.username }}"
          echo "Repository Name: ${{ inputs.reponame }}"

      - name: Create Repository from Template
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEMPLATE_REPO: "Frentzen/spring-boot-3-rest-api-template"
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$TEMPLATE_REPO/generate \
            -d "{
              \"owner\": \"${{ inputs.username }}\",
              \"name\": \"${{ inputs.reponame }}\",
              \"description\": \"New repository created by workflow\",
              \"private\": false
            }"

      - name: Confirm Repository Creation
        run: echo "Repository ${{ inputs.reponame }} created successfully for user ${{ inputs.username }}!"
